### ISSUE TITLE
Says sync failed when it seeming worked just fine

### ISSUE THREAD

**Issue by The-Ducktor** [AChep/keyguard-app#10]
It says the sync failed even tho I syncing everything from what I could tell prehaps the ability to hide the button might be nice

**Comment by AChep** [comment]
If you head to Settings / Accounts / Account you should see more detailed error message. Sync status is a bit lackluster at this moment.

**Comment by The-Ducktor** [comment]
After I made. This I saw Thier was a "unsupported item" that says can't sync because it can't be unencrypted I can delete or edit the said thing so that might be causing the problem.
![Screenshot_20230923-085842~2.png](https://github.com/AChep/keyguard-app/assets/130664593/f19e7543-566d-45bb-8cde-6ae86ac007ee)

**Comment by AChep** [comment]
@The-Ducktor oh, very interesting. How old is your account? Could you make a redacted screenshot of the same item in the Bitwarden app? Does it belong to some old organization, or maybe some new one?

**Comment by The-Ducktor** [comment]
The account isn't old and it's my personal/default vault but I used a script because I used proton for a bit so that could be the error that the official ones just ignore and the apps just hide it I can't find the error on the official app so nor on the web client it's a self host with a vaultwarden instance if that makes a difference if I connect to my older official instance account no such error  haven't touch it in months

**Comment by AChep** [comment]
> The account isn't old and it's my personal/default vault but I used a script because I used proton for a bit so that could be the error that the official ones just ignore and the apps just hide it I can't find the error on the official app so nor on the web client it's a self host with a vaultwarden instance. If that makes a difference if I connect to my older account on official instance account no such error haven't touch it in months haven't touch it
> 
> 
> Small Update Tried exporting the vault then putting it in another vault get another one of the “Unsupported Error” so it's something in my vault i just can't find what that thing is
> 
> Larger Update: Found The unknown login through Trial and error, and i have no idea what your wonderful app finds wrong with this login. I could just delete if it's
> 
> 
>  just a random temp thing but im confused on what it considers wrong. ![Screenshot 2023-09-23 135656](https://github.com/AChep/keyguard-app/assets/130664593/fcaef92e-b75d-4fc5-851f-09630fc3e235)
>  Im greatly confused on why this exact one doesn't want to work but  the only thing i can think is that it's incomplete but other are also that way so yea
> 

Probably for some weird reason the script used a different but still supported method of encryption for this one. I'll try to investigate a bit more 

You can delete that one and create the same new item, it should fix the warning on Keyguard's side.

**Comment by The-Ducktor** [comment]
No i just did as a unencrypted one "it's to the same server didn't feel like it made much difference" but sure would be happy to help.

**Comment by AChep** [comment]
@The-Ducktor any chance you could share the JSON entry of that item? It should have the same name as in the Web vault. You can redact username, password. Would be awesome if you could do that.

Is the 'error' folder yours?

**Comment by The-Ducktor** [comment]
Yes the error folder is mine i was during the finding what one was the erroring one interesting that your app can see the folder it's in but not the contents or the name or anything niethier can i change the folder but it can see what the folder is who knows

on a more important note sure i can give the login to see if you have a similer issue tried it and got the same error with this file or at least with the direct file this found out name of the of the thing didn't make a difference when doing copying magic
Start:
{
  "encrypted": false,
  "collections": [
    {
      "id": "caf15d67-a4ea-467c-b303-351723ac3167",
      "organizationId": "8559dcc7-ebd5-452d-9105-733c2674e00a",
      "name": "Default collection",
      "externalId": null
    }
  ],
  "items": [
    {
      "id": "bb468803-cb90-4054-aa79-768019dd8ce4",
      "organizationId": "8559dcc7-ebd5-452d-9105-733c2674e00a",
      "folderId": null,
      "type": 1,
      "reprompt": 0,
      "name": "errormaster",
      "notes": null,
      "favorite": false,
      "login": {
        "uris": [
          {
            "match": 0,
            "uri": "adguard"
          },
          {
            "match": null,
            "uri": null
          }
        ],
        "username": "bob@bob.bob",
        "password": "hackme",
        "totp": null
      },
      "collectionIds": [
        "caf15d67-a4ea-467c-b303-351723ac3167"
      ]
    }
  ]
}
:Finish
Tried it and it import's just fine to the server but same "unsupported item Ignore the start/finish parts would do it another way but can't upload files eh GitHub issue if you need the direct file i could do it another way if needed

**Comment by AChep** [comment]
@The-Ducktor thanks a lot! I was able to reproduce it on my end as well! It seems like the empty URI is what makes Keyguard fail the decoding. Should be fixed on Monday :)

**Comment by AChep** [comment]
The build with a fix is in review now, should be available in 1-4 hours.
