### ISSUE TITLE
Allow Custom Fields to be affected by the "concealed fields" settings

### ISSUE THREAD

**Issue by The-Ducktor** [AChep/keyguard-app#11]
make it so you could have conceal fields  for custom fields and not only default ones
<img width="378" alt="Screenshot 2023-09-24 at 7 52 46 AM" src="https://github.com/AChep/keyguard-app/assets/130664593/1764a534-8de1-4608-898b-f6f8dccb684f">

**Comment by AChep** [comment]
@The-Ducktor when creating/editing a custom field, tap a three dots button and check 'conceal value'.

**Comment by The-Ducktor** [comment]
Thanks sorry I didn't see that option.
