### ISSUE TITLE
Username Disappears But Updates to Server When Changed or Added

### ISSUE THREAD

**Issue by The-Ducktor** [AChep/keyguard-app#12]
When you add a username to a identity it saves to the server but immediately removes itself from keyguard but can be seen in other apps to the changes made
To me this appears to be unintended behavior 

https://github.com/AChep/keyguard-app/assets/130664593/a12e5176-10df-4fc5-9c9b-88a310bd1930

<details>
<summary>Image of the same item in bitwarden's official app after changing stuff in keyguard</summary>

![Screenshot_20230924-121605](https://github.com/AChep/keyguard-app/assets/130664593/f0c83ed1-a381-446c-a8b9-276fc00eaa51)

</details>

**Comment by AChep** [comment]
Fixed in the internal build. The fix should be available in a production build in a few days.
