### ISSUE TITLE
Feature Request: Hide Subscription After Purchase (Low Priority)

### ISSUE THREAD

**Issue by The-Ducktor** [AChep/keyguard-app#13]
Hide the subscription option if the one-time purchase has already been made. Currently, attempting to purchase the subscription when you already own the aforementioned one-time purchase is not possible at least in my experience. This improvement aims to declutter the interface without major disruptions, enhancing the user experience.
<details>
<summary>Screenshot</summary>

![Screenshot_20230924-194110](https://github.com/AChep/keyguard-app/assets/130664593/85abd28a-7a01-425b-8a0a-47a28627d689)

</details>

**Comment by AChep** [comment]
Hmm, that should actually be possible, to have both subscription and a lifetime offer. What error does it say if you click on the subscription offer?

**Comment by The-Ducktor** [comment]
> Hmm, that should actually be possible, to have both subscription and a lifetime offer. What error does it say if you click on the subscription offer?

![some Google error](https://github.com/AChep/keyguard-app/assets/130664593/d5c2e8c9-5671-4f6d-9af2-9b1ae3661acf)

**Comment by AChep** [comment]
I'd rather leave both: in case you already have subscription active, you should still see the status. And if you don't have it active, maybe you feel like a one-time purchase is not enough to support the development :beers:

**Comment by The-Ducktor** [comment]
fair points still get the error when clicking on the subscription so that might be something that should be fixed

**Comment by AChep** [comment]
> fair points still get the error when clicking on the subscription so that might be something that should be fixed

Was able to find something that probably caused that bug. Hopefully it will be resolved with the next update (probably next week).

**Comment by AChep** [comment]
@The-Ducktor could you confirm that the error is gone now? 😊

**Comment by The-Ducktor** [comment]
yes it no longer gives a error when clicking on the subscription
