### ISSUE TITLE
Option to "Autofill and save"

### ISSUE THREAD

**Issue by yurividal** [AChep/keyguard-app#137]
Hi. When i am using autofill, and for some reason the uri is not saved, and I search for the item from the vault, Bitwarden has an option to "autofill" and one option to "autofill and save" (which adds the current uri to that vault item). Keyguard doesn't seem to have this. Any chance this can be implemented?

**Comment by AChep** [comment]
Do you have Settings / Autofill / Auto-save app or website info option enabled?

**Comment by yurividal** [comment]
I didn't have it. I do have it now. Didn't know it was an option. Sorry.
Still, maybe it would be nice to have the option to do it per-item, like bitwarden. sometimes you do want to save it, sometimes it's a one-off... i dont know, just an idea. Thanks anyway! I'll close this.

**Comment by AChep** [comment]
Yeah, might be a nice addition to add Autofill and save to the dropdown menu in the full screen.

**Comment by AChep** [comment]
Should be done with https://github.com/AChep/keyguard-app/commit/80318722c558e0442e41991b7b352d13cc4e4bd0
