### ISSUE TITLE
Inconsistent whitespace triming of app passwords

### ISSUE THREAD

**Issue by favonia** [AChep/keyguard-app#138]
I accidentally discovered this weird bug. Using an app password starting or ending with space characters will not work. To reproduce, here are the steps:

1. Use an app password that ends with a space, say `aaaaaa `.
2. Lock the vault.
3. Try to unlock the vault with `aaaaaa ` or `aaaaaa` (none would work).

My theory is that Keyguard has (correctly) trimmed app passwords in most cases but the untrimmed passwords were (incorrectly) used for encryption. I think trimming makes perfect sense, a practice recommended by NIPS, but it was not consistently done.

**Comment by AChep** [comment]
Nice find! Most likely it's trimmed on the Unlock vault screen but not trimmed at the Change password screen. Gotta unify that.
