### ISSUE TITLE
Delete original items after merge in Watchtower

### ISSUE THREAD

**Issue by The-Ducktor** [AChep/keyguard-app#14]
I suggest enhancing the watchtower duplication feature to include an option for automatically deleting the original items when merging duplicates. Currently, when I use the "Show Duplicates" feature, it simply creates more copies, which is less effective. This proposed change will streamline password management, eliminating old duplicates and creating a merged entry.

I believe this change aligns with the concept of merging, where two items become one, rather than creating a third item with combined data.

**Comment by jeffconrad18** [comment]
Adding this would be really useful!

**Comment by AChep** [comment]
I think that is already implemented as an option. Check 'Move origin items to trash' during the merge process.
