### ISSUE TITLE
Sometimes the app might treat another thing as username by mistake

### ISSUE THREAD

**Issue by xuangeyouneihan** [AChep/keyguard-app#15]
Some Chinese websites choose to let users to log in with a one-time password sent via SMS, and users need to click on a button to log in with password. Take [知乎/Zhihu](https://www.zhihu.com) for example:

![IMG_20230927_155814](https://github.com/AChep/keyguard-app/assets/50788434/6899d0de-3d6c-4293-8c5d-669b5dcfccc1)

![IMG_20230927_155446](https://github.com/AChep/keyguard-app/assets/50788434/52671c83-0294-4a03-a2e4-6fe0aad52219)

The thing is, in some browsers, like [狐猴浏览器/Lemur Browser](https://lemurbrowser.com/app) or [Kiwi Browser](https://kiwibrowser.com), Keyguard can only fill in EITHER username in the first page OR password in the second page, while the official Bitwarden app can autofill both username and password correctly. I don't know whether it is Keyguard's problem, but I'd appreciate it if you could solve it!

**Comment by AChep** [comment]
I did find that for some reason the type of the username field is 'text' in Kiwi. I did adjust the code to fix it and it seemed to work... but you can not be 100% sure with the Autofill code.

Speaking about adjusting the autofill, could you add text phrases in Chinese that hint that the field is username or password? for example, in English these are:

for Password:
- password 

for Username:
- username
- nickname
- login

this could also help with the detection.

**Comment by AChep** [comment]
@xuangeyouneihan please check if it's fixed in the latest build.

**Comment by xuangeyouneihan** [comment]
Name: Simplified Chinese 1 (Traditional Chinese 1) / Simplified Chinese 2 (Traditional Chinese 2) / …

Password: 密码 (密碼)
OTP: 验证码 (驗證碼) / 一次性密码 (一次性密碼)

Username: 用户名 (用戶名)
Phone number: 手机 (手機) / 手提电话 (手提電話) / 手机号 (手機號) / 手机号码 (手機號碼) / 电话 (電話)/电话号 (電話號) / 电话号码 (電話號碼)
Email: 电子邮箱 (電子郵箱) / 邮箱 (郵箱) / 电邮 (電郵)
(Phone number and email can be username)

Nickname: 昵称 (暱稱)

Log in: 登录 (登錄) / 登陆 (登陸) /登入

Log out: 退出 / 注销 (註銷) / 登出

P.S. I think it's better to use some converter that can turn Traditional Chinese to Simplified Chinese, for different characters can have different code points. Take 说 (say/speak) for example, in Simplified Chinese (zh-CN), it's 说 (U+8BF4); in Traditional Chinese (Hong Kong) (zh-HK), it's 説 (U+8AAC); and in Traditional Chinese (Taiwan) (zh-TW), it's 說 (U+8AAA).

**Comment by AChep** [comment]
Thanks! Did the previous update fix it for you? Or is it still the same on your end?

**Comment by xuangeyouneihan** [comment]
> @xuangeyouneihan please check if it's fixed in the latest build.

> Thanks! Did the previous update fix it for you? Or is it still the same on your end?

I've updated the app. It works, but only on [Zhihu](https://zhihu.com). Here are some "similar" websites:
-

**Comment by xuangeyouneihan** [comment]
I've updated the app. It works, but only on [Zhihu](https://zhihu.com). Here are some "similar" websites:

- https://m.bilibili.com
- https://m.weibo.cn
- https://taobao.com
- https://h5.meituan.com
- https://baidu.com

**Comment by AChep** [comment]
Should be improved in the next tomorrow's update.

**Comment by xuangeyouneihan** [comment]
So shall I know when the update will be released?

**Comment by AChep** [comment]
> So shall I know when the update will be released?

It should already be live 😃

**Comment by xuangeyouneihan** [comment]
Thank you! Another question: Is purchase information stored locally? Google is banned in China, and I'm afraid  that I can't add a password to the vault without using proxy services.

**Comment by AChep** [comment]
> Thank you! It works. Another question: Is purchase information stored locally? Google is banned in China, and I'm afraid that I can't add a password to the vault without using proxy services.

Last successful Google's IAP response is cached locally, so the app _should_ keep last Premium status without access to internet (or Google). I did not however test for this use case, so I can't really guarantee that this is how it gonna work

**Comment by xuangeyouneihan** [comment]
Well, I think the loss of premium status might be caused by a cleaning module on my phone, however there is also another problem: I just used Alipay to pay for my meal, and then Keyguard asked me to save the "username", which is the amount of money I need to pay😂

![IMG_20231001_172738](https://github.com/AChep/keyguard-app/assets/50788434/96adac69-febc-4e66-aebf-474807f6e0b7)
