### ISSUE TITLE
Enable Multiple Domains for Server on the Same Account

### ISSUE THREAD

**Issue by The-Ducktor** [AChep/keyguard-app#17]
I have a somewhat specific feature request: I'd like the ability to associate multiple domains with a single account or server. However, I want to ensure that the entries are not duplicated. Specifically, I envision having one primary domain and the option to set up a backup domain. This would be useful for scenarios where the main domain might encounter issues for reasons that might seem magical, and while this isn't an urgent request, it would be a valuable addition.

**Comment by AChep** [comment]
Is that something like a fallback server? E.g. each entry is gonna be synced to both servers.

**Comment by The-Ducktor** [comment]
yes something along those lines

**Comment by AChep** [comment]
What's your use case that your server is sometimes inaccessible through the primary domain and still accessible through the secondary domain? The first thing that comes to my mind is difficulty accessing the server though the primary domain via the same WiFi network.

**Comment by The-Ducktor** [comment]
I said oddly specific mostly a backup when my tunnels break and would be nice to be have to have the local domain still sync anything but a fallback server would most likely be a better idea

**Comment by AChep** [comment]
This can be a very low priority feature, but I'd say that it probably won't come. 
- Syncing to multiple servers would be super painful, as the IDs of the items on different servers are all different.
- Domain thingie feels like it should be done on the router instead.

**Comment by The-Ducktor** [comment]
I recognize the challenges, and there may be more pressing priorities; feel free to close the issue if it won't be pursued
