### ISSUE TITLE
F Droid Package Request

### ISSUE THREAD

**Issue by CompeyDev** [AChep/keyguard-app#191]
Currently keyguard is only available on Play Store, which isn't the most privacy concious or open source platform. 

I request you to file a packaging request for F Droid, which is a more preferred app store for open source projects like keyguard.

**Comment by AChep** [comment]
Duplicate of https://github.com/AChep/keyguard-app/issues/78

**Comment by CompeyDev** [comment]
My bad, I searched for "F Droid" and didn't find the issue. Sorry.

**Comment by CompeyDev** [comment]
My bad, I searched for "F Droid" and didn't find the issue. Sorry.
