### ISSUE TITLE
Usernames do not autofill

### ISSUE THREAD

**Issue by carlosaya** [AChep/keyguard-app#198]
I just installed this and really want to use it, but on many sites it is just refusing to autofill my username.  I am on a Pixel 8 using Chrome browser and inline autofill in gboard.

Some example sites:

https://ib.nab.com.au/login
https://banking.westpac.com.au/

...and on these it is showing logins for completely different sites than the one I am trying to login on:

https://member.secure.australianretirementtrust.com.au/login
https://portal.australiansuper.com/login

The official Bitwarden client for Android works as expected for these same sites.  Any help would be appreciated.  Thanks!  🙏

**Comment by AChep** [comment]
@carlosaya does it not show the suggestion for the site, or does it also show a bunch of non relevant ones? What is your URL added in the login itself?

**Comment by carlosaya** [comment]
The autofill only comes up when I go to the password field.  If I select it then only the password gets populated.

The sites in my vault for these entries are...

https://ib.nab.com.au/nabib/index.jsp
androidapp://au.com.nab.mobile

http://banking.westpac.com.au
androidapp://org.westpac.bank

https://member.secure.australianretirementtrust.com.au/login?returnUrl=/&utm_source=welcome&utm_medium=email&utm_campaign=mjo_welcome&utm_content=mol_login
androidapp://com.sunsuper.prod

**Comment by AChep** [comment]
@carlosaya gotcha. As for the 

> on these it is showing logins for completely different sites than the one I am trying to login on:

does it not show the correct suggestion at all, or shows it + a bunch of irrelevant ones?

**Comment by carlosaya** [comment]
Not sure what changed, but the first link now works fine.  The second one still shows an unrelated login for my electric company.

URI for my electric company vault entry:

https://globirdcustomerportalprod.azurewebsites.net

**Comment by AChep** [comment]
What is the URL set for the login of https://portal.australiansuper.com/login ? Do you have any custom equivalent domains set?

**Comment by carlosaya** [comment]
I actually don't have any entries in my vault for that website 😅   I went to the wrong website by mistake.  It still doesn't make sense that Keyguard was providing my electric company login details though.  I have seen this behavior on other sites as well, though I can't remember the details right now.  Sorry, not much help there.

**Comment by AChep** [comment]
It should now correctly autofill username/id field.

**Comment by carlosaya** [comment]
Confirmed working. Thank you!
