### ISSUE TITLE
[Feature] Open links in default browser

### ISSUE THREAD

**Issue by flexagoon** [AChep/keyguard-app#20]
Currently, Keyguard opens all links in the in-app browser. Most apps that do this offer a setting to disable it and use a proper browser instead. It would be nice if Keyguard also had such a feature.

**Comment by AChep** [comment]
Just curious, why would you want to open a link in a full browser window instead?

**Comment by flexagoon** [comment]
The in-app browser doesn't support tabs. which means you can't a link from the website you visit in a new tab, you can't quickly switch to a different tab to search for something, etc. It also doesn't have proper history support, and you can't click on the URL bar to modify the current URL.

**Comment by AChep** [comment]
Should be available in the next update.
