### ISSUE TITLE
Long items' names cut on top

### ISSUE THREAD

**Issue by n4zk4** [AChep/keyguard-app#207]
I noticed that with items that have long names (displayed on two rows in item view), the name is not shown correctly, as in it's cut on top. It's noticeable once I tap on an item to view its content (not on the main list). Can it be fixed? It seems to be a UI issue: probably the top bar (with edit and back button) is overlapping on the name box.

In the screenshot  I obviously scrolled all the way to the top to try and show the full name.

![image](https://github.com/AChep/keyguard-app/assets/144371645/94cbd637-ff4a-43eb-b6c8-1aa3b690d755)

**Comment by AChep** [comment]
Can be tested here: https://github.com/AChep/keyguard-app/actions/runs/8666430807 @n4zk4

**Comment by n4zk4** [comment]
@AChep the APK you linked fixed the issue. Thank you!
