### ISSUE TITLE
Bitwarden annouced a new app for Android

### ISSUE THREAD

**Issue by korpe1** [AChep/keyguard-app#208]
Bitwarden just annouced a new app for Android on [Reddit post](https://www.reddit.com/r/Bitwarden/comments/1b32bbz/going_native_the_future_of_the_bitwarden_mobile/). The new app is made with Kotlin and follow the guidelines of Material design, just like Keyguard. What do you think about it? Would is be possible to cooperate and bring the efforts together? Also, to make this, would it be possible to make Keyguard open-source under GPL v3, MIT or Apache v2 licenses?

**Comment by AChep** [comment]
It looks better than the existing app, but I still like Keyguard more. To me the new so looks like big performance improvements + reskin to material components. Which is good, you don't want to scare the regular users with the redesign too much.

Merging codebases would mean that I have to donate all existing code + 1 year worth of work to contribute it to their project to the Bitwarden company.

I love Bitwarden but not that desperately. 🥲

**Comment by korpe1** [comment]
> It looks better than the existing app, but I still like Keyguard more. To me the new so looks like big performance improvements + reskin to material components. Which is good, you don't want to scare the regular users with the redesign too much.

Maybe but it's very early and them are more features and underneath more powerful.

> Merging codebases would mean that I have to donate all existing code + 1 year worth of work to contribute it to their project to the Bitwarden company.

I think cooperation should still be considered. Maybe, Bitwarden could hire you or pay you for making this open-source? You have made good work in the user interface.

> I love Bitwarden but not that desperately. 🥲

My opinion is that we need a wide truly open-source ecosystem. Clients should be developed in cooperation and be universal as possible. Vaultwarden should be grow even more.

**Comment by AChep** [comment]
> I think cooperation should still be considered. Maybe, Bitwarden could hire you or pay you for making this open-source? You have made good work in the user interface.

I'm up for that if Bitwarden wants it. So far I don't really think they do :smile:
