### ISSUE TITLE
Application startup password

### ISSUE THREAD

**Issue by KangodYan** [AChep/keyguard-app#217]
Every time the keyguard is launched, it requests the input of the application password. Is it possible to provide an option to not require inputting the password at startup.

**Comment by AChep** [comment]
There's an option to persist the vault key on a disk.

**Comment by KangodYan** [comment]
I noticed this option before. I use the Chinese interface, and it says '密码库将在后台被杀后锁定', My understanding of it was that the keyguard process would be locked after being killed, but it's not the case. Based on your reply, I enabled this option and found that the keyguard process is not locked even after being killed. So, I have reason to believe that the wording of this option caused me confusion.

**Comment by AChep** [comment]
I think the summary text of that option changes based on the current switch's value. Not sure if that is a good idea anymore. 😅

**Comment by KangodYan** [comment]
Oh, I have an idea. This option has two rows, and the currently effective one can always be displayed on top. In other words, every time the switch is toggled, the text in the two rows will swap positions.
