### ISSUE TITLE
[Feature] Username generator 

### ISSUE THREAD

**Issue by flexagoon** [AChep/keyguard-app#22]
The official Bitwarden client has a feature to generate random usernames from a word and 4 random digits, eg. combust0715

**Comment by AChep** [comment]
Should be there in the next build. Functionally it's the same as Passphrase generator, just with a different default settings.

**Comment by flexagoon** [comment]
@AChep thanks for adding the feature! There is one small issue though, if you click on the `✨` button when entering a username for a new login, it opens the password generator by default instead of the username generator

**Comment by AChep** [comment]
It will open the last selected type
