### ISSUE TITLE
Unsupported item: failed to decode cipher text

### ISSUE THREAD

**Issue by favonia** [AChep/keyguard-app#224]
I encountered the same error as in #10 and unfortunately I don't remember the things I created or modified right before seeing the message. (I was using the web vault before seeing the message on my phone.) Please let me know how to assist your debugging. Thanks. Here's a screenshot that unfortunately doesn't seem to be very useful (I blacked out my account name).

![keyguard](https://github.com/AChep/keyguard-app/assets/1471328/3c598ef1-700f-472f-85e5-4ffeb8b9c52c)

**Comment by AChep** [comment]
Do you know what item that corresponds to on the web vault?

**Comment by favonia** [comment]
> Do you know what item that corresponds to on the web vault?

I can check that when I have more time (not right now... maybe not even before May). Is there any tip to find the item quickly?

**Comment by AChep** [comment]
> > Do you know what item that corresponds to on the web vault?
> 
> I can check that when I have more time (not right now... maybe not even before May). Is there any tip to find the item quickly?

I will add something to help finding the item in the next build.

**Comment by favonia** [comment]
@AChep Looking forward to it! Please let me know in this issue so that I can help. Thank you again for this great app.

**Comment by AChep** [comment]
@favonia here's a build that should show more info about the failing cipher: https://github.com/AChep/keyguard-app/actions/runs/8454266958

**Comment by AChep** [comment]
> @AChep I unzipped the artifact and tried to install the `apk` file but my phone blocked it (without saying why) :thinking: Unfortunately I don't have more time now to figure out what exactly was going wrong. (I already granted the permissions to install apps from unknown sources.)

The latest store version should already have that feature, so you can just update it. 

Below the error message you will see the .JSON blob with all the encrypted fields.

**Comment by favonia** [comment]
@AChep Hmm here's something weird---the sync error was magically gone?! If you didn't add new decryption ability, I'm afraid I accidentally destroyed the test case :exploding_head: One possibility I could think of is that I updated the offending entry via browsers...

**Comment by AChep** [comment]
> @AChep Hmm here's something weird---the sync error was magically gone?! If you didn't add new decryption ability, I'm afraid I accidentally destroyed the test case :exploding_head: One possibility I could think of is that I updated the offending entry via browsers...

I did add support for per-cipher encryption. Also added a condition that "" (empty string) should be decrypted as an "". Maybe that helped in your case, or you modified the entry and that fixed it.

If it happens again, feel free to re-open the issue 🙂
