### ISSUE TITLE
[suggestion] Allow Standard / Custom Filters to fit on one line (if display names are short enough).

### ISSUE THREAD

**Issue by BJReplay** [AChep/keyguard-app#231]
I renamed Identity to ID and One Time Passwords to OTP, in the hope that all five standard filters would fit on one line.  On my phone (S22U), One Time Passwords is always on a second line.

However, with the shorter names, the first four (Card, Identity, Login, and Note) are spread out more on the first line with additional whitespace between items, rather than allowing the shortend One Time Passwords (OTP) to fit on the first line.

It looks like the first four items are always displayed on the first line and the fifth (and possibly any custom) item on a second line.

No screenshots as screenshots are prevented by the app.

**Comment by AChep** [comment]
All of the filters there are equal and custom. You can also remove them if you don't need a particular one. 

Btw, you can allow screenshots in the settings for this use case 😅

**Comment by BJReplay** [comment]
I like all five filters - I use them - but I'd like them to fit on one line if possible.  There's room with shorter names, but it looks like they don't flow onto just one line.  Feel free to close.

**Comment by AChep** [comment]
> I like all five filters - I use them - but I'd like them to fit on one line if possible.  There's room with shorter names, but it looks like they don't flow onto just one line.  Feel free to close.

What might also be an option is to delete existing custom filters and create the same new ones. I do not support picking an icon for the new ones yet, so the new ones will be iconless this taking less space 😀

**Comment by BJReplay** [comment]
Will close, no longer required.
