### ISSUE TITLE
Why can't I sync to Bitwarden? I'm using the premium version of Playstore.

### ISSUE THREAD

**Issue by r0krwi** [AChep/keyguard-app#234]

**Comment by AChep** [comment]
Does it show an error or something?

**Comment by r0krwi** [comment]
![Screenshot_20240330-163702.png](https://github.com/AChep/keyguard-app/assets/63093115/afb04359-7636-4089-a77f-d928b91449ee)

**Comment by AChep** [comment]
I saw the screenshot, thanks! I had to delete it to not expose your usernames. If you click on the Sync failed button and then follow it, can you see any info about the failure?

**Comment by r0krwi** [comment]
OH！ Thank you for your thoughtfulness and when i manul i click the sync button here writte Bad Request ：invalid_grant.
Maybe I could log in again?

**Comment by AChep** [comment]
> OH！ Thank you for your thoughtfulness and when i manul i click the sync button here writte Bad Request ：invalid_grant. Maybe I could log in again?

Yep, there should be a floating action button to sign in.

**Comment by r0krwi** [comment]
> > OH！ Thank you for your thoughtfulness and when i manul i click the sync button here writte Bad Request ：invalid_grant. Maybe I could log in again?
> 
> Yep, there should be a floating action button to sign in. 

Thank you so much that I have successfully synced. I think it may be because I am not an English speaker. I didn't pay attention when the prompt was prompted.
