### ISSUE TITLE
Overlapping text when creating a new item

### ISSUE THREAD

**Issue by JordyEGNL** [AChep/keyguard-app#236]
Hi, the title and help text is overlapping when creating a new item, see attached screenshot.

![Screenshot_20240330-121754_Keyguard.png](https://github.com/AChep/keyguard-app/assets/65036298/5af4c2e3-10b0-4e98-b30f-52417288a61e)

App version
1.0.0-120900004.release

App build date
30 maart 2024

App build ref
8cd3b2b

**Comment by AChep** [comment]
Should be fixed with https://github.com/AChep/keyguard-app/commit/7c9d9c10221f449d2ca424bd63a8e2a04a53f602 in tomorrow's release. :beers:
