### ISSUE TITLE
Maybe it's my problem! More than 200 items were added under a single password, resulting in a direct crash when clicked to modify

### ISSUE THREAD

**Issue by A3148475824** [AChep/keyguard-app#238]
It seems that more than 200 changes in the project will flash back, although I have more than 3,500 passwords, there are only a dozen passwords, because of the addition of a large number of projects, the modified content will crash, so I still hope that developers can optimize it!

**Comment by AChep** [comment]
Sorry, I didn't completely understand what the problem was. 

Is it a performance issue or something else?

**Comment by A3148475824** [comment]
> Sorry, I didn't completely understand what the problem was.对不起，我不完全明白问题出在哪里。
> 
> Is it a performance issue or something else?是性能问题还是其他问题？

Performance problem!
I added a new project, but it added more than 200 "custom fields", if to modify the content will crash the software!
![Screenrecorder-2024-03-31-13-14-08-272_小萌GIF_20240331_131721](https://github.com/AChep/keyguard-app/assets/70214970/54a65573-d985-4e5b-bcee-b1f5988f69df)

**Comment by AChep** [comment]
Gotcha! I'll check if I can easily fix it, thanks!

**Comment by A3148475824** [comment]
> Gotcha! I'll check if I can easily fix it, thanks!明白了！我会检查我是否可以轻松修复它，谢谢！

Thank you

**Comment by A3148475824** [comment]
> @A3148475824the build with a fix can be found here:可以在此处找到带有修复程序的构建：[https://github.com/AChep/keyguard-app/actions/runs/8646110247https://kithub.com/achab/gaykwart-up/actions/run/8646110247](https://github.com/AChep/keyguard-app/actions/runs/8646110247)it should improve the performance and possibly fix the crash,它应该提高性能并可能修复崩溃，

Thank you very much. Upon seeing the news, I will immediately test it and it will not crash. Thank you 🙏 Developer!
