### ISSUE TITLE
When I try to set up biometric authentication/unlock, it shows 'Keystore operation failed'

### ISSUE THREAD

**Issue by smloli** [AChep/keyguard-app#240]
When I set up biometric authentication/unlock, it prompts 'Keystore operation failed'
[![B697-C19-CFC7-A4-D438923305629479333.jpg](https://i.postimg.cc/9MsDVBpW/B697-C19-CFC7-A4-D438923305629479333.jpg)](https://postimg.cc/r0CVNx3b)

**Comment by AChep** [comment]
What device & OS version are you on? Does a phone reboot help?

**Comment by smloli** [comment]
> What device & OS version are you on? Does a phone reboot help?

The phone model Samsung Galaxy S20 Ultra with Android 11 system version gives the same prompt when restarting the device or reinstalling the software

**Comment by AChep** [comment]
@smloli did it get resolved by it itself?

**Comment by smloli** [comment]
> @smloli它自己解决了吗？

The system is working properly after I updated it; there must have been an issue with the system I installed before.
