### ISSUE TITLE
Cipher must have an account error when trying to create item

### ISSUE THREAD

**Issue by mihneaCR** [AChep/keyguard-app#241]
Hi,

just discovered the app, feels great and the autofill actually works, bought the premium license immediately.

Upon trying to create an item though, the following error appears, and the item is not created:

![Screenshot_2024-04-01-01-17-54-754_com artemchep keyguard](https://github.com/AChep/keyguard-app/assets/47532611/874f090c-32a6-469a-867b-1e13bbf495bd)

I am trying to connect to a self-hosted vaultwarden instance, the access logs do not indicate anything as far as I can tell.

If there is anything I can do to assist debugging this problem please let me know. 

Thanks in advance!

**Comment by AChep** [comment]
Fixed with https://github.com/AChep/keyguard-app/commit/06d2ea60057f9f46f945eb2952b6b856e2725334

Meanwhile you can click on the No account text in top of the screen and select an amount 😀
