### ISSUE TITLE
Howto Update Windows Version

### ISSUE THREAD

**Issue by celevra** [AChep/keyguard-app#243]
Hi,

i use the Windows Version also.
No i downloaded the newest release but it has no version incrementation, its still version 1.0.0
If i try to install it via double click, it tells me that it is allready installed.
The only way seems to uninstall it via system settings and then install it from the download.
There must be a simpler way, isn't it?

regards

**Comment by AChep** [comment]
Should work for future upgrades from 20240503 release.
