### ISSUE TITLE
Bug: Autofill modal closes when backing out after checkbox selection

### ISSUE THREAD

**Issue by PalmDevs** [AChep/keyguard-app#26]
Ideally the modal shouldn't close but deselect every single item. Going back again will then finally close the modal.

For context, I'm referring to this specifically:

![Contextual screenshot](https://github.com/AChep/keyguard-app/assets/67689562/097620ce-1bfd-4a91-93ab-3dacd53fe32a)

**Comment by AChep** [comment]
Agree, this should really be implemented on every screen with selection.
