### ISSUE TITLE
App not opening

### ISSUE THREAD

**Issue by rohitghali** [AChep/keyguard-app#261]
I've been using the app all these days. Worked well. It now stopped opening. I tried uninstalling and installing. Didn't work. What's going on?

**Comment by AChep** [comment]
If it crashes immediately on start, then an ADB logcat would be super helpful. Just make sure to filter by error level and cut everything that happens before the crash and after.

**Comment by PlumpAlbert** [comment]
Rebooting my phone solved the issue

**Comment by rohitghali** [comment]
> Rebooting my phone solved the issue

That worked. Thanks.
