### ISSUE TITLE
Autofill no longer works

### ISSUE THREAD

**Issue by flexagoon** [AChep/keyguard-app#280]
Keyguard no longer offers autocomplete on any websites, I have to manually copy and paste my account info

**Comment by AChep** [comment]
What browser & OS are you on?

**Comment by flexagoon** [comment]
@AChep Android (GrapheneOS), [Vanadium](https://vanadium.app) (Chromium)

**Comment by flexagoon** [comment]
Oh, turns out Chrome released an update and you have to explicitly enable "allow other autofill providers" in chrome settings to use anything except Google's password manager
