### ISSUE TITLE
Passkeys does′t work on Android 14

### ISSUE THREAD

**Issue by JasonHK** [AChep/keyguard-app#281]
The passkeys work fine using the Bitwarden browser extension on desktop, but does′t work with Keyguard on Android 14.

https://github.com/AChep/keyguard-app/assets/4410086/1b991c92-1a3d-4c65-ad3b-225246d615a9

**Comment by AChep** [comment]
Go to the entry that contains a passkey, tap on the passkey and check the signature counter. For it to properly work the counter should be 0. If it is not, recreate the passkey and it should now always be at zero.

**Comment by JasonHK** [comment]
@AChep Thanks, it works now. Curious why this would happened.

**Comment by AChep** [comment]
> @AChep Thanks, it works now. Curious why this would happened.

Oh, it's fairly simple. Initial Bitwarden's implementation used the signature counter, which is not a great idea, so they abandoned it a few months ago.

https://www.reddit.com/r/Bitwarden/s/Ta2i1KYRvL
