### ISSUE TITLE
Bug: Password/username generator repositions itself when refresh

### ISSUE THREAD

**Issue by danielphan2003** [AChep/keyguard-app#3]
See this:

https://github.com/AChep/keyguard-app/assets/34669737/72c859e8-e1ac-4508-825a-734edf2f8611

**Comment by AChep** [comment]
I managed to workaround the issue by ensuring that the content of the bottom sheet always has max height. It seems to be a bug of Jetpack Compose. 

See: https://issuetracker.google.com/issues/297974040

**Comment by AChep** [comment]
Keeping this issue to track the bug and close it after I change the Compose version to the one that contains a fix.
