### ISSUE TITLE
Bug: Scrim/overlay does not extend to unsafe areas

### ISSUE THREAD

**Issue by PalmDevs** [AChep/keyguard-app#30]
Completely cosmetic, would be nice to have it fixed though!

Look at the top of the screenshot where the colors are still bright:

![Screenshot of the issue](https://github.com/AChep/keyguard-app/assets/67689562/a4facbd6-c56f-4c97-9f73-abe7468ae9a9)

What it should've looked like (from another app):

![Screenshot of what the fix should look like](https://github.com/AChep/keyguard-app/assets/67689562/7cc2785d-7229-4de4-9816-3ef2deb30326)

**Comment by AChep** [comment]
Seems like with what Compose's Bottom Sheet component currently offers there's no way to fix it properly. :disappointed: Will wait for the improvements in the component, I think they planned to revisit those modals in the future releases, as there are a plenty of issues with them.
