### ISSUE TITLE
"Incorrect username or password" when logging into Bitwarden. 

### ISSUE THREAD

**Issue by Xisrr1** [AChep/keyguard-app#303]
I've tried multiple times and even changed my Bitwarden password, Keyguard will still show incorrect.

**Comment by AChep** [comment]
Is the selected region correct?

**Comment by Xisrr1** [comment]
Tried .com and .eu, both didn't work.

**Comment by AChep** [comment]
> Tried .com and .eu, both didn't work.

Uh, is https://vault.bitwarden.com/ the site you usually login into? Other than that I can really only recommend clicking on the eye icon and double checking that the email and password are both correct and do not contain any whitespaces.

**Comment by AChep** [comment]
What I meant is that if outside of Bitwarden you login into https://vault.bitwarden.com/ then you should select Unites States (.com) region, if you login into https://vault.bitwarden.eu/ then you should select Europe (.eu) region. If you self-host Bitwarden or login into someone's Bitwarden then you should select Custom and enter the correct URLs there.

**Comment by Xisrr1** [comment]
I've tried again and now it did sign in. Maybe it was an outage? I tried more than 10 times and surely did it correctly.

**Comment by AChep** [comment]
That's weird. Glad it got resolved tho!

**Comment by Xisrr1** [comment]
> That's weird. Glad it got resolved tho!

Thanks. I'm a new user so I have a few questions:

Does keyguard requests to save passwords after I log into an account on an app or website? 

When it prompts to save a password or use a password, does it work in a popup like Google password manager and Samsung Pass? Asking because the official Bitwarden app opens every time you save a password instead of a small popup to save. 

And lastly, does the GitHub build offer free premium? It seems it doesn't show premium as an option. 

Thanks for the fast response!
