### ISSUE TITLE
A few questions about keyguard:

### ISSUE THREAD

**Issue by Xisrr1** [AChep/keyguard-app#304]
Does keyguard requests to save passwords after I log into an account on an app or website?

When it prompts to save a password or use a password, does it work in a popup like Google password manager and Samsung Pass? Asking because the official Bitwarden app opens every time you save a password instead of a small popup to save.

And lastly, does the GitHub build offer free premium? It seems it doesn't show premium as an option.

**Comment by AChep** [comment]
> When it prompts to save a password or use a password, does it work in a popup like Google password manager and Samsung Pass? Asking because the official Bitwarden app opens every time you save a password instead of a small popup to save.

For now it opens full screen.

> And lastly, does the GitHub build offer free premium? It seems it doesn't show premium as an option.

Yes, but I can't promise that it will not change in a long term.

**Comment by Xisrr1** [comment]
Thanks for the fast responses.

**Comment by AChep** [comment]
No problem :)
