### ISSUE TITLE
Login issue presist 

### ISSUE THREAD

**Issue by Xisrr1** [AChep/keyguard-app#305]
Hey again, sorry for bothering you too much. Now when I try again it will show "incorrect username or password"  every time I try to log in. The correct email and password were entered.

**Comment by AChep** [comment]
A build with a fix should be here https://github.com/AChep/keyguard-app/actions/runs/8928433035 withing a 20 minutes. Please check if it solves the issue!

**Comment by Xisrr1** [comment]
I have no idea how to use this build but after a few tries it does sign in. Annoying tho.

**Comment by AChep** [comment]
Did you manage to install it? Or does it sign in with the build from the Google play store if you try a couple of times?

**Comment by Xisrr1** [comment]
I have no idea where it is in the link you provided

**Comment by AChep** [comment]
A build with a fix is currently in review on Play store.

**Comment by AChep** [comment]
It should be available now.

**Comment by Xisrr1** [comment]
> It should be available now.

Yes I'll test

**Comment by Xisrr1** [comment]
I tried and it worked the first time so I think it's fixed.
