### ISSUE TITLE
Quetta Browser

### ISSUE THREAD

**Issue by SaschMie** [AChep/keyguard-app#306]
Please add the quetta Browser for autofill.

net.quetta.browser
https://play.google.com/store/apps/details?id=net.quetta.browser

Thank you

**Comment by SaschMie** [comment]
Hi there, i saw you added the browser. Autofill seems still not to work?

**Comment by prirai** [comment]
Can confirm, the browser still doesn't seem to be getting autofill. @SaschMie did you seem to get a workaround?

**Comment by SaschMie** [comment]
Yes it is still not working, nothing happens on a pw field.

**Comment by prirai** [comment]
> Yes it is still not working, nothing happens on a pw field.

It seems the browser itself has not implemented native autofill, not keyguard's fault. Quetta is bringing that in the newer updates, an initial version was already pushed but its not working well.
