### ISSUE TITLE
Chrome auto fill targets address bar

### ISSUE THREAD

**Issue by BSoDium** [AChep/keyguard-app#31]
On Android 14 running on a pixel 7, when auto filling in chrome using the gboard password manager integration, the username/email is often set in the address bar (Top URL bar) instead of the correct username field on the web page for some reason.

This is kind of frustrating and defeats the purpose of this feature.

As a sidenote, if this can help with reproducible the bug, I also have developer tools enabled with predictive animations turned on.

**Comment by AChep** [comment]
Thanks for reporting it! Could you please provide an example of a website where it happens?

**Comment by BSoDium** [comment]
After trying again, I have only managed to reproduce the part where the url address bar gets targeted, but the username now auto fills correctly. I've attached a screenshot for clarity:
![Screenshot_20231111-235323](https://github.com/AChep/keyguard-app/assets/46868627/b501e65c-5785-429c-877c-2a7091fbf768)

> This happens on the Chrome stable version, right?

Yes, absolutely, Chrome 119.0.6045.67 to be precise

**Comment by AChep** [comment]
Should be fixed in the next update. Thank you for reporting it!
