### ISSUE TITLE
PC version can't login：unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by magisk317** [AChep/keyguard-app#320]
I have a local self-hosted environment ，
and have configured relevant key files. 

### The web is OK：
![image](https://github.com/AChep/keyguard-app/assets/93979778/2ae67e97-7cbd-4a8d-ac19-6c89ea41821f)

### keyguard mobile is OK：
![image](https://github.com/AChep/keyguard-app/assets/93979778/bfc96bce-db90-4828-9b29-eb51367d26e8)

### and official PC bitwarden client is also OK：
![image](https://github.com/AChep/keyguard-app/assets/93979778/5ed92e2a-569f-4519-9b49-8f4ecc8a9857)

However, the PC version of keguard does not work and cannot be logged in. The error message is as shown in the title:
```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
![image](https://github.com/AChep/keyguard-app/assets/93979778/d8885fba-9506-4b57-8f4f-1624a57a092e)

**Comment by AChep** [comment]
The solution is probably similar to https://github.com/AChep/keyguard-app/issues/63

**Comment by magisk317** [comment]
OK，it‘s done
