### ISSUE TITLE
[feature request]TOTP preview in the main list

### ISSUE THREAD

**Issue by magisk317** [AChep/keyguard-app#323]
You can refer to [keepassdx](https://github.com/Kunzisoft/KeePassDX), and the interface is as follows:
![Screenshot_20240505-121549](https://github.com/AChep/keyguard-app/assets/93979778/ba7580c3-72db-461c-a658-ba6a171552d8)

Click to copy directly without opening specific items.

**Comment by AChep** [comment]
TOTP codes will show up in the list if you apply a TOTP filter.

**Comment by magisk317** [comment]
> TOTP codes will show up in the list if you apply a TOTP filter.

Well, it can really achieve the same effect.
