### ISSUE TITLE
[BUG] Cannot use passkeys (Xiaomi)

### ISSUE THREAD

**Issue by Cyber2525** [AChep/keyguard-app#326]
Phone says "no passkeys in this device" but passkeys are saved on key guard/bitwarden

**Comment by crim50n** [comment]
> Enable android credentials flag to third party passkeys

I am using Android 14 on Samsung Galaxy S24 Ultra, when trying to authenticate with Passkey I get an error `privilegedAllowlist must be formatted properly` in Keyguard.

**Comment by AChep** [comment]
> > Enable android credentials flag to third party passkeys
> 
> I am using Android 14 on Samsung Galaxy S24 Ultra, when trying to authenticate with passkey I get an error `privilegedAllowlist must be formatted properly` in Keyguard.

Fixed by https://github.com/AChep/keyguard-app/pull/527
