### ISSUE TITLE
Whether matching apps should be ranked based on application installation time

### ISSUE THREAD

**Issue by A3148475824** [AChep/keyguard-app#332]
Every time I add a password, I match the application, and I see that all the applications are arranged, but in alphabetical order! But for normal people, they add passwords only because they have installed a new application. The ranking order should be based on the application installation time, not alphabetical! What I need is that the apps installed now are at the top of the list! There's no way I need to swipe down to alphabetical query or search! Of course, this is not a bug, but it will affect physical experiments! It can only be said that it is optional, and if there is any, it can improve the experience!
I am just providing my thoughts, and of course if you feel that my tone makes you feel incomprehensible, disgusted or angry, I am sorry! What you see is the result of translation or the translation may be incorrect. I just propose an improvement plan! Developers can choose to ignore it or include it in follow-up plans

**Comment by JordyEGNL** [comment]
That's a great idea!

Maybe a filter icon could be added (just like on the home page) to filter on app installation time or most recently used apps. If it it not possible to show all apps I think that's okay..

**Comment by AChep** [comment]
Closed by https://github.com/AChep/keyguard-app/commit/d17bff174958da33efdfa22cfb3a27ef55a8d2d2
