### ISSUE TITLE
Logging in says Unusual traffic error (error code 7)

### ISSUE THREAD

**Issue by PalmDevs** [AChep/keyguard-app#34]
I'm unsure why it does that. The Bitwarden web vault works, and so does their Android app. This seems to be a Keyguard-specific issue. If it helps, I'm getting the error code 7.

**Comment by AChep** [comment]
In theory they could add something to their requests that they specifically tell Cloudflare to look for. In that case more and more users should start having this issue (me included) which will allow me to copy-paste the parameters and find the offender. At this moment it's unknown if they do it, let's see if it resolves itself or not.

**Comment by PalmDevs** [comment]
Alright, the issue seems to have resolved itself. Very odd that the normal Bitwarden clients work and not custom ones. I'll close this now.

**Comment by CerebralDatabank** [comment]
I am having the same issue. The official clients and website work fine, but no amount of switching to other mobile networks or VPN servers gets rid of Error 7 in Keyguard.

Surely the app is not sending user passwords through its own proxy or something?

**Comment by AChep** [comment]
@CerebralDatabank nope, but it sends the bare minimum of stuff Bitwarden requires.

**Comment by PalmDevs** [comment]
> I am having the same issue. The official clients and website work fine, but no amount of switching to other mobile networks or VPN servers gets rid of Error 7 in Keyguard.

No VPN would work, simply wait for a day or two and it will resolve itself. Try to login first try though, otherwise it might flag you again.

**Comment by DVDAndroid** [comment]
I have the same issue. Tried 2 different accounts and 2 different IP. I have installed the app on the emulator, enabled mitmproxy and captured the HTTP request to Bitwarden:

```
POST https://vault.bitwarden.com/api/accounts/prelogin HTTP/2.0
bitwarden-client-name: web
bitwarden-client-version: 2023.10.1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.77 Chrome/70.0.3538.77 Safari/537.36
accept: application/json
accept-charset: UTF-8
content-type: application/json
content-length: 45
accept-encoding: gzip
```
with JSON body:
`{"email":"email"}`

I have tried it in Postman (with the same headers) and I got the same error if I used that User-Agent header; with another User-Agent it works without problems.
Only these headers are required: `Content-Length`, `Host`, `Accept` and `Content-Type`


Same goes for `https://vault.bitwarden.com/identity/connect/token` request

**Comment by AChep** [comment]
> I have the same issue. Tried 2 different accounts and 2 different IP. I have installed the app on the emulator, enabled mitmproxy and captured the HTTP request to Bitwarden:
> 
> ```
> POST https://vault.bitwarden.com/api/accounts/prelogin HTTP/2.0
> bitwarden-client-name: web
> bitwarden-client-version: 2023.10.1
> user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.77 Chrome/70.0.3538.77 Safari/537.36
> accept: application/json
> accept-charset: UTF-8
> content-type: application/json
> content-length: 45
> accept-encoding: gzip
> ```
> with JSON body:
> `{"email":"email"}`
> 
> I have tried it in Postman (with the same headers) and I got the same error if I used that User-Agent header; with another User-Agent it works without problems.
> Only these headers are required: `Content-Length`, `Host`, `Accept` and `Content-Type`
> 
> 
> Same goes for `https://vault.bitwarden.com/identity/connect/token` request
> 

What user agent did you try?

**Comment by DVDAndroid** [comment]
- None
- "Keyguard"
- something random

**Comment by AChep** [comment]
Interestingly enough I had to set it to that value because of the Cloudflare in the first place. Maybe I should go a bit deeper and make it even more realistic...

**Comment by DVDAndroid** [comment]
I've also intercepted official Bitwarden app and it uses these headers:
```
Device-Type: 0
Bitwarden-Client-Name: mobile
Bitwarden-Client-Version: 2023.9.1
User-Agent: Bitwarden_Mobile/2023.9.1 (Android 9; SDK 28; Model AOSP on IA Emulator)
Accept-Encoding: identity
Host: vault.bitwarden.com
```

_(ignore old Bitwarden version)_

**Comment by AChep** [comment]
I will publish an update this night that uses latest user agent from Chrome/Linux: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`. Hopefully that fixes this issue for most of users.

**Comment by DVDAndroid** [comment]
> `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`

Just tested it and it works (for me)

**Comment by CerebralDatabank** [comment]
Thanks for the fast initial response to my comment! I saw it but didn't get a chance to reply :)

> I will publish an update this night that uses latest user agent from Chrome/Linux: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`. Hopefully that fixes this issue for most of users.

Unfortunately, I still get the same error today. I don't know if the update is live yet, though.

**Comment by AChep** [comment]
> Thanks for the fast initial response to my comment! I saw it but didn't get a chance to reply :)
> 
> > I will publish an update this night that uses latest user agent from Chrome/Linux: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`. Hopefully that fixes this issue for most of users.
> 
> Unfortunately, I still get the same error today. I don't know if the update is live yet, though.

The update wasn't live it the time you've commented. Should be live now :smile:

**Comment by CerebralDatabank** [comment]
Yep, it works now! 😄

**Comment by PalmDevs** [comment]
Hooray!
