### ISSUE TITLE
Keyboard at the entrance

### ISSUE THREAD

**Issue by srcarkk** [AChep/keyguard-app#344]
Hello, I would like an option in the settings that allows my keyboard to be opened whenever, after I enter the app password, the search for logins starts. Similar to what Aegis Auth already has as an option.
![aegisoption.jpeg](https://github.com/AChep/keyguard-app/assets/82451852/84710bd3-734c-4e29-a701-5a58ddb320cf)

**Comment by AChep** [comment]
On the Vault screen, click on the menu icon and enable Always show keyboard. This should do the trick

**Comment by srcarkk** [comment]
Thanks, I've never seen that option before lol 😅
