### ISSUE TITLE
Email generators don't work without account

### ISSUE THREAD

**Issue by DVDAndroid** [AChep/keyguard-app#36]
I have not logged in any Bitwarden account, but I can still use other features of the app.
When I try to use "Catch-all email", "Plus addressing email" or "Subdomain addressing email" it won't show any email.

<details>

![Screenshot_1700513056](https://github.com/AChep/keyguard-app/assets/6277172/d0e8c6e1-c6c0-4f3a-8971-db44b10504ce)

</details>

After a Bitwarden login, they work normally
<details>

![Screenshot_1700513117](https://github.com/AChep/keyguard-app/assets/6277172/c21f7e3b-0e11-4f57-8cbf-5562cf5e1fd6)

</details>

---
version `1.0.0-118200001.release`

**Comment by AChep** [comment]
If you scroll down a bit, on the first screenshot you can see that the "Domain" has a red outline. It is required for the generator to work.

**Comment by DVDAndroid** [comment]
Yeah, sorry by bad
