### ISSUE TITLE
"Failed to authorize a request" error when using passkeys on Firefox Nightly

### ISSUE THREAD

**Issue by JasonHK** [AChep/keyguard-app#364]
When trying to use passkeys to login to websites using Firefox Nightly, an "Failed to authorize a request" error with a message of "Origin is not being returned as the calling app did notmatch the privileged allowlist" appears instead.

![Screenshot_20240528_141008_Keyguard](https://github.com/AChep/keyguard-app/assets/4410086/6121e265-d680-46e3-b87e-2e651eaf5af6)

**Comment by AChep** [comment]
Keyguard is using a privileged apps list created by Google which apparently doesn't include Firefox Nightly. While I'm against including all _random_ browsers into this list I think Firefox is trustworthy enough.
