### ISSUE TITLE
Bug: Linked fields always show it's linked to password

### ISSUE THREAD

**Issue by PalmDevs** [AChep/keyguard-app#37]
Pretty self explanatory. When adding a linked field to a login, Keyguard lets you select whether it's linked to a username or a password. The problem comes when it's actually displaying it. It always shows `[x] linked to password` even when the field is actually linked to username.

**Comment by AChep** [comment]
Good catch! Will fix it in the next build!

**Comment by PalmDevs** [comment]
@AChep Hey there, I recently just updated to `1.0.0-118350001-release` and I'm still having the same issue.

![Screenshot_20231202_134343_Keyguard](https://github.com/AChep/keyguard-app/assets/67689562/fe515a00-ca47-4b2c-b230-cb5d2bea35de)

**Comment by AChep** [comment]
@PalmDevs argh, I set password to use the username label and username to use the password label by a mistake :yum:
