### ISSUE TITLE
Clouldn't sync the account: invalid_grant

### ISSUE THREAD

**Issue by mindrunner** [AChep/keyguard-app#375]
I have been using keyguard for a while now. Everything seemed fine so far. Today I was missing some entries in my Bitwarden app. Turned out that keyguard has silently stopped working without giving me any notice about this. The error I see in the account settings is: `Couldn't sync the account: invalid_grant`

Last sync was almost 8 weeks ago!

How can I re-enable sync such that I do not lose the local state?
How can I make sure this does not happen again?

**Comment by AChep** [comment]
The account screen where you see an error should have a button to sign in again. If you use it, local changes will be not be lost. You can also export local items first just in case.

**Comment by mindrunner** [comment]
Stupid me! Thanks so much :)
