### ISSUE TITLE
50 char complex Keyguard vault password won't work for extracting a zip backup

### ISSUE THREAD

**Issue by mannp** [AChep/keyguard-app#385]
Hi there

I have a zip backup from Keyguard that I am trying to restore in Bitwarden, but I cannot extract the contents of the Keyguard zip file.

I am using the Keyguard vault password rather than anything to do with Bitwarden, is that correct?

Is there a restriction on the length of the backup zip password at all, as my vault password is 50 chars with special characters.

The password works fine with Keyguard.

Thanks.

**Comment by AChep** [comment]
Hi,

There's no restriction on the passwords length but it seems like 96 characters might be the max number after which I'm no longer able to un-zip the archive.

I've tested it with the password `@|+^6#-2!!5@9+-%-+6583=62_3-|9_*!92+?=-!$=28!*9_^%-%&_3-56=3|5?__?3?8859=+-976#9-6-|696@9&_$@` (are there any more weird symbols in your password?) and it worked fine. You can try to use other archive program to unzip the file.

**Comment by AChep** [comment]
I've tried to use another archive managers and those did just fine with 128 characters password: `u:xw*MPNs++`V"HIg@&`+-\Wtp"H@hXY{z">!5lpUgD\C!]*TF6|qoTpN6qeyu=1}+Ki.$d{6:Fgau1h)L-<dw3pcdvPT4&4B*d$K#02pHAl.zVx4Y/T5(6UQNS6nt;!`

**Comment by mannp** [comment]
That's very odd then, not what i was thinking it was.

Thanks you for testing that out, I will have to go back and try with another archive manager.

**Comment by AChep** [comment]
Feel free to ping me if other archive managers do not work too 🙂
