### ISSUE TITLE
Invalid symbol ''(0) at index 3

### ISSUE THREAD

**Issue by BJReplay** [AChep/keyguard-app#392]
OS: Windows 11 Pro
App: Keyguard 1.2.0
New Database (New Windows Profile)
Added first account successfully.
Went to add second account - assumed it was by clicking on Settings - error message displayed with title `Error` and message `Invalid symbol ''(0) at index 3` and button `OK`

Clicking on OK closes the program.

Reopening the program and entering the vault password opens the program correctly, but clicking on settings causes the error to appear.

Most other tools, including Watchtower appear to work as expected.

P.S. Watchtower mark as read is Fantastic 👍

![image](https://github.com/AChep/keyguard-app/assets/37993507/0f958143-82a3-4c99-8ca0-3628fafc9819)

![image](https://github.com/AChep/keyguard-app/assets/37993507/0299a2b6-59e4-4e33-b119-6fca36a0ee59)

**Comment by AChep** [comment]
Should be fixed in the Compose https://github.com/JetBrains/compose-multiplatform/issues/4938
