### ISSUE TITLE
[QUESTION] Where does keyguard get my profile picture from? /How to update it

### ISSUE THREAD

**Issue by ITron-Legends** [AChep/keyguard-app#412]
If it's from Google I've already updated it.. unless it's getting from some other site.
![Screenshot_2024-06-15-16-21-27-17_f2500aab0c419d0d79426db9ab76c5a4](https://github.com/AChep/keyguard-app/assets/130519797/13bd9dd7-0564-4519-8bbf-e08f2d35c774)

**Comment by AChep** [comment]
gravatar.com
