### ISSUE TITLE
Scoop package install support

### ISSUE THREAD

**Issue by nitrocode** [AChep/keyguard-app#424]
Similar to #118 for Windows

Scoop is a windows package manager (similar to choco)

Related https://github.com/ScoopInstaller/Extras/issues/13476

The end result would be a single command to install the app

```bash
scoop install keyguard
```

**Comment by AChep** [comment]
Added a [PR](https://github.com/ScoopInstaller/Extras/pull/14348) with the working keyguard.json

**Comment by AChep** [comment]
Closed by https://github.com/AChep/keyguard-app/commit/80cfdfec796ed1f9cc1194ba3f8bbd106e6ab38c

**Comment by nitrocode** [comment]
Thanks!
