### ISSUE TITLE
Autofill not working on all apps

### ISSUE THREAD

**Issue by omarashraf307** [AChep/keyguard-app#432]
I have this banking app of my bank called QNB bebasata.
And the autofill worked perfectly with bitwarden and even when I used proton pass.
but for some reason it doesn't work at all with keyguard app.
It's never detected for autofill from the keyboard

**Comment by AChep** [comment]
Do you enable accessibility service when using Bitwarden autofill?

**Comment by omarashraf307** [comment]
Nope
It's not enabled

**Comment by AChep** [comment]
I've tested the app and found that the system doesn't receive autofill requests when you are on a login screen. Neither Keyguard nor Bitwarden worked for me. This should be fixed in the QNB bebasata app itself.

**Comment by CaptechOmar** [comment]
I hope I can reopen this issue because I tested different password manager apps like Bitwarden and proton pass and they all worked with this app
They gave me an autofill options
But for some reason it's not working with keyguard
