### ISSUE TITLE
feat: use a different package name for the f-droid version

### ISSUE THREAD

**Issue by polymo1** [AChep/keyguard-app#456]
Hello again!

I enjoy using Keyguard for my Vaultwarden instance.

I have one gripe, google play doesn't like to play nice with Keyguard regarding updates. I cannot currently pay for Keyguard Premium, if I could I would.

Would it be possible to use a different app/package ID for the fdroid version to avoid conflict with Google Play?

**Comment by AChep** [comment]
Related to https://github.com/AChep/keyguard-app/issues/117 I don't want to maintain >1 package names for each app store we have.

**Comment by polymo1** [comment]
Ah that's my bad. I hadn't looked to see if there were previous related issues. Keep up the great work!

On Jul 9, 2024 13:41, Artem Chepurnyi ***@***.***> wrote:

Related to #117<https://github.com/AChep/keyguard-app/issues/117> I don't want to maintain >1 package names for each app store we have.
