### ISSUE TITLE
Misspelling in german translation

### ISSUE THREAD

**Issue by TgZ39** [AChep/keyguard-app#481]
![grafik](https://github.com/user-attachments/assets/89009279-d0a4-4e1c-9a4f-cfd8ee1b94d6)

The correct spelling of `1 Hour` in german is `1 Stunde` (https://www.dict.cc/?s=Stunde)

**Comment by AChep** [comment]
Thanks! Keyguard is localized by the community. Feel free to suggest a fix here: https://crowdin.com/editor/keyguard/22581/en-de
