### ISSUE TITLE
Why are some key features locked behind a paywall?

### ISSUE THREAD

**Issue by driftywinds** [AChep/keyguard-app#495]
Things like multiple accounts and two way sync already exist in the official app, why would I use this if it puts those features behind a paywall? 
Does the GitHub release of this app have those features unlocked?

**Comment by AChep** [comment]
> Things like multiple accounts and two way sync already exist in the official app, why would I use this if it puts those features behind a paywall? 

The app is developed solely by me and not connected to the official app. The paywall is both a Thank you and a motivational speech to me to continue working on the app.


> Does the GitHub release of this app have those features unlocked?

Yes
