### ISSUE TITLE
Editing some items with Keyguard strips URLs

### ISSUE THREAD

**Issue by griffi-gh** [AChep/keyguard-app#498]
I noticed that after editing some items with Keyguard, all associated URIs and apps get removed from them and only visible in Keyguard, not normal Bitwarden app or browser extension. (This also completely prevents autofill from working in the Firefox extension).

The only way to add URIs back is using the official client (and never using keyguard to edit any entries again)

**Comment by AChep** [comment]
Should be fixed in the next build. To make the URI appear on Biwarden official clients again edit anything in the entry again using Keyguard.
