### ISSUE TITLE
Cannot complete initial sync: "Failed to decode a cipher-text"

### ISSUE THREAD

**Issue by langerdennis** [AChep/keyguard-app#53]
When trying to perform the initial sync against my self-hosted Vaultwarden installation, I get the following error message:

`Failed to decode a cipher-text: UserToken, symmetric key is 64b long, asymmetric key is 1219b long`

The app correctly asks me for user/password and 2FA for my user, but afterwards fails to sync. I am exposing the docker container through Caddy as a reverse proxy, with Cloudflare tunnel establishing the connection to the proxy. The official apps work flawlessly though, so not sure if that chain might cause any problem. Whenever I try to add the account from Keyguard (entering the 2FA while doing so), my Vaultwarden instance shows the following logs:

_[2024-01-05 15:25:21.150][error][ERROR] 2FA token not provided
[2024-01-05 15:25:21.150][response][INFO] (login) POST /identity/connect/token => 400 Bad Request
[2024-01-05 15:25:38.145][request][INFO] POST /api/accounts/prelogin
[2024-01-05 15:25:38.145][response][INFO] (prelogin) POST /api/accounts/prelogin => 200 OK
[2024-01-05 15:25:38.293][request][INFO] POST /identity/connect/token
[2024-01-05 15:25:38.314][vaultwarden::api::core::two_factor::authenticator][ERROR] Invalid TOTP code! Server time: 2024-01-05 14:25:38 UTC IP: <redacted>
[2024-01-05 15:25:38.314][response][INFO] (login) POST /identity/connect/token => 400 Bad Request
[2024-01-05 15:26:14.148][request][INFO] POST /api/accounts/prelogin
[2024-01-05 15:26:14.148][response][INFO] (prelogin) POST /api/accounts/prelogin => 200 OK
[2024-01-05 15:26:14.273][request][INFO] POST /identity/connect/token
[2024-01-05 15:26:14.297][vaultwarden::api::identity][INFO] User <redacted> logged in successfully. IP: <redacted>
[2024-01-05 15:26:14.297][response][INFO] (login) POST /identity/connect/token => 200 OK
[2024-01-05 15:26:14.444][request][INFO] GET /api/sync?excludeDomains=true
[2024-01-05 15:26:14.480][response][INFO] (sync) GET /api/sync?<data..> => 200 OK_

Any idea why those calls fail? The difference between local time shown and UTC of the server is expected, and Bitwarden official apps do accept the 2FA.

**Comment by AChep** [comment]
The server log looks fine. I'd focus on the error message from the client: it tells us that it failed to decrypt the vault. Keyguard doesn't support older encryption methods that were used in Bitwarden before (_I simply don't have an account that has that_ :disappointed:). While rotating the key / changing the password should help, it would be amazing if we could try to find out what's preventing it from the sync :)

**Comment by mannp** [comment]
Just got the same error trying to add bitwarden.com account.

Cheers.

**Comment by AChep** [comment]
@langerdennis @mannp could you try again with this version? https://github.com/AChep/keyguard-app/actions/runs/7538993845 It has a better error message that may help me fix the issue.

**Comment by langerdennis** [comment]
Unfortunately I will have to wait for the Play Store version, since I am on a corporate device with sideloading apks forbidden by policy 🫤

**Comment by mannp** [comment]
> @langerdennis @mannp could you try again with this version? https://github.com/AChep/keyguard-app/actions/runs/7538993845 It has a better error message that may help me fix the issue.

@AChep installed and can see a long error, but there seems to be no way of copy and pasting the sync error out. Will have a better look later, as out atm.

**Comment by AChep** [comment]
> > @langerdennis @mannp could you try again with this version? https://github.com/AChep/keyguard-app/actions/runs/7538993845 It has a better error message that may help me fix the issue.
> 
> @AChep installed and can see a long error, but there seems to be no way of copy and pasting the sync error out. Will have a better look later, as out atm.

Oh, so your error message doesn't contain the "symmetric key is Nb long, asymmetric key is Nb long" part? What is the X value you have in the error "Failed to decode a cipher-text 'X.????'"?

**Comment by mannp** [comment]
> "Failed to decode a cipher-text 'X.????'"?

6.eGdTR......

...failed to decode the cipher text with the type '6': User Token, symmetric key is 64b long....asymmetric 1216b long

**Comment by AChep** [comment]
@mannp any better luck with this build? https://github.com/AChep/keyguard-app/actions/runs/7543888473 Added the support for decoding the missing cipher type, but I have nothing to test it on.

**Comment by mannp** [comment]
> @mannp any better luck with this build? https://github.com/AChep/keyguard-app/actions/runs/7543888473 Added the support for decoding the missing cipher type, but I have nothing to test it on.

Yes @AChep that worked fine, and I was able to sync without issue. Thanks 👍🏻

**Comment by AChep** [comment]
@langerdennis a build with a potential fix should be on Play Store now.

**Comment by langerdennis** [comment]
The new version worked for me as well! Thanks so much for fixing, will test and go premium 👍

**Comment by kattelk** [comment]
I am also getting a "Failed to decode a cipher-text" error message:

"Failed to decode a cipher-text with the type '0:
AuthToken, . Failed to decode a cipher-text '0.???'!
Cause: pad block corrupted"

Do you know what might be causing this message?

**Comment by AChep** [comment]
> I am also getting a "Failed to decode a cipher-text" error message:
> 
> "Failed to decode a cipher-text with the type '0:
> AuthToken, . Failed to decode a cipher-text '0.???'!
> Cause: pad block corrupted"
> 
> Do you know what might be causing this message?
> 

How old is that Bitwarden account? Does Keyguard not sync any items, or some still appear?

**Comment by kattelk** [comment]
The account is nearly 6 years old. No items are synced.

**Comment by AChep** [comment]
> The account is nearly 6 years old. No items are synced.

Okay, that's good to know. I'll try to either provide a build that outputs more information or try to fix it blindly.
