### ISSUE TITLE
[Feature Request] OTP for Steam

### ISSUE THREAD

**Issue by nSucrose** [AChep/keyguard-app#536]
I want to transfer my password book to this manager, but its OTP seems to be incorrect. If this manager can support OTP for Steam, then I don't need to use KeePass separately

**Comment by AChep** [comment]
It already supports Steam OTP, just use the `steam://SECRET` schema.

**Comment by nSucrose** [comment]
Thank you.It can now run correctly.

**Comment by PuffinRub** [comment]
> use the `steam://SECRET` schema

Are there any others that might be interesting?

**Comment by AChep** [comment]
> Are there any others that might be interesting?

In general, the app supports 
- `otpauth://`
- `steam://`
- `motp://`
schemas. The regular `otpauth://` also has partial support for counter based codes (`hotp`), where you will be able to see a correctly generated code, but won't be able to easily increment the counter.

**Comment by ShaunWuu** [comment]
> ... but won't be able to easily increment the counter.

When will it get supported? I'm eager to this feature~Thanks~
