### ISSUE TITLE
[Enhancement] Antivirus warning

### ISSUE THREAD

**Issue by Cyber2525** [AChep/keyguard-app#539]
Windows feature

Show a warning screen or dialog warning when opening the keyguard while having the antivirus off or having something in the in the antivirus whitelist classified as "remote acces virus"

The title: Risks Found
Description: "Having your antivirus off or allowed malware may compromise the vault"

The warning has 2 options and one checkbox:

First: Close keyguard (button)
Second: Slide to ignore risks (slide a red circle like iOS call app or iOS powermenu)

Checkbox: Don't warn again

**Comment by Cyber2525** [comment]
If u don't like the idea, I can adjust it to be more convenient, don't simply close it

**Comment by Cyber2525** [comment]
It's an extra security feature, also you have the checkbox to disable the warning, do u know that is token and vault stalker? Ratters and so many more? If the vault is compromised, all your accounts are stolen

I mean a feature for windows

**Comment by rushiiMachine** [comment]
The best antivirus that exists is your own common sense...

**Comment by Cyber2525** [comment]
Not all people is as smart as you and there are virus that are too well designed... This is just another security thing


This is all your accounts in one vault, so it needs to be the as much safe as posible

That's the Dev decision

**Comment by AChep** [comment]
Having an antivirus enabled might be a good thing, but it's also not a magical cure that ensures that the vault never gets stolen. 0-days exist, users who click on random .exe files exist too. The vault is only safe if you put a computer in a bunker underground and never plug or connect anything to it and even then, the good old 5$ wrench will get all your passwords.

![image](https://github.com/user-attachments/assets/d6cee792-628c-4c74-9f6f-70a351facef8)
https://xkcd.com/538/
