### ISSUE TITLE
flatpak requires gnome45

### ISSUE THREAD

**Issue by Geertsky** [AChep/keyguard-app#552]
Trying to install keyguard on rocky9 complains"
`error: The application com.artemchep.keyguard/x86_64/master requires the runtime org.gnome.Platform/x86_64/45 which was not found`

Installing with `--no-deps` shifts the problem to starting the app.

**Comment by FunProgramer** [comment]
Did you already add the flathub repo? I don't know if it's added by default in rock9.
In any case you could run:
```sh
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

**Comment by AChep** [comment]
Well, Keyguard's flatpak requires GNOME platform to be installed:  https://flathub.org/apps/org.gnome.Platform
