### ISSUE TITLE
No Response When Selecting Autofill in Termux for Password Field

### ISSUE THREAD

**Issue by sodabyte** [AChep/keyguard-app#594]
**Description:**

In Termux, when attempting to autofill a password using the Keyguard app, there is no response after selecting the autofill option. This happens specifically when:

1. **Steps to reproduce:**
   - Open Termux.
   - Navigate to a password field.
   - Long press the field > More > Autofill Password.
   - Observe that no action occurs after selecting Keyguard autofill.

2. **Expected behavior:** 
   The autofill should provide the relevant login details from Keyguard.

3. **Actual behavior:** 
   No response when selecting Keyguard autofill.

4. **Additional notes:**
   This issue appears to be specific to Keyguard, as autofill works without issue using other password managers like:
   - Bitwarden (official app)
   - KeepassDX
   - Keepass2Android
   - 1Password (tested a year ago)

**Comment by AChep** [comment]
How do you navigate to a password field in Termux?

**Comment by sodabyte** [comment]
In Termux, I'm referring to a scenario where a command like `rclone config` prompts for a password because the config is encrypted. When Termux requests the password, autofill doesn't automatically pop up. To access autofill, I long press the Termux screen, select "More...", and then choose "Autofill password". With other password managers (e.g., Bitwarden, KeepassDX, Keepass2Android), this method works, and I see inline suggestions for compatible passwords. However, with Keyguard, after selecting the autofill option, there is no response or any password suggestions.
