### ISSUE TITLE
Discussion: Allow editing folders from folder items view

### ISSUE THREAD

**Issue by PalmDevs** [AChep/keyguard-app#6]
If a vault item is assigned a folder, viewing its information will show you its assigned folder. Clicking on it will navigate to the folder items view which only displays the list of the vault items that is assigned to that specific folder, but editing is not allowed. An edit feature should be provided instead of the user needing to go to Settings > Accounts > (the account) > Folders > (the folder) > Edit, which is a bit long.

**Comment by AChep** [comment]
Sounds nice to have and should be fairly easy to add. Will try to include it in the next update 😀

**Comment by AChep** [comment]
Will be available in the next update. On the list view there will be an option to rename the Folder.
