### ISSUE TITLE
[Feature Request] Automatically wrap notes in the project

### ISSUE THREAD

**Issue by ThemanRonin** [AChep/keyguard-app#604]
As shown in the image, notes within the keyguard project do not automatically wrap. In reality, I have multiple lines of text, but they are all displayed on one line, causing the text to be jumbled and difficult to read. The official project notes wrap normally. It is recommended to add a feature that allows automatic line wrapping for project notes in keyguard.

![image](https://github.com/user-attachments/assets/5fd5dd9e-53cb-4f49-8157-c11f1d229120)

**Comment by AChep** [comment]
You should disable Markdown support in Keyguard settings to get the same behavior as Bitwarden.
