### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by dontobi** [AChep/keyguard-app#614]
I am using the current Keyguard version and have noticed that a dialog is not displayed in my language (German).

![Screenshot_20241003-101837~2](https://github.com/user-attachments/assets/2d244a52-678c-4e4c-b50b-55aee15d7f5d)

**Comment by AChep** [comment]
@dontobi thanks for noticing! I move those lines to the translatable resources, now they can be translated here https://crowdin.com/editor/keyguard/22573/en-de?view=comfortable&filter=basic&value=0

**Comment by dontobi** [comment]
I have just added the German translation to crowdin.
