### ISSUE TITLE
[BUG] Passkey not working on Cloudflare

### ISSUE THREAD

**Issue by JordyEGNL** [AChep/keyguard-app#635]
When trying to log in to the Cloudflare Dashboard on https://dash.cloudflare.com  the passkey login flow gets redirected to the Keyguard app but the response from Cloudflare is "Invalid security key used. Please use a security key registered to this account".

https://github.com/user-attachments/assets/dcc73e13-d187-4c05-8d0a-bf1208423b8d

When trying the same with the Bitwarden Beta app (the native one on 2024.9.0) it works as expected. With the same passkey.

https://github.com/user-attachments/assets/ae5f48cc-0cc3-437c-b4f1-cb353001a4a3

https://github.com/user-attachments/assets/9407ab45-7851-4d13-a1d2-4af6e082a406

Passkeys from Keyguard DO work on https://myaccount.google.com so passkeys are working on Keyguard :)

**Comment by AChep** [comment]
What is the Signature counter for this passkey? You can view it in Keyguard by clicking it.

**Comment by JordyEGNL** [comment]
> What is the Signature counter for this passkey? You can view it in Keyguard by clicking it.

Its currently at 50 and will increase every time I log it with the official browser extension

**Comment by AChep** [comment]
Are you perhaps using an old extension version? I believe Bitwarden gave up on using the signature counter and I've never implemented the support for it.

**Comment by JordyEGNL** [comment]
> Are you perhaps using an old extension version? I believe Bitwarden gave up on using the signature counter and I've never implemented the support for it. 

I'm using 2024.10.0 on Firefox and it is adding 1 to the counter every time I use it

**Comment by AChep** [comment]
You should create a new passkey. If the counter is >0 then Bitwarden has to increment it.

**Comment by JordyEGNL** [comment]
> You should create a new passkey. If the counter is >0 then Bitwarden has to increment it (and Keyguard doesn't support it).

Thanks! Will try that

**Comment by JordyEGNL** [comment]
Can confirm that removing the passkey with the signature counter being more than 0 and recreating the passkey fixed the issue!
