### ISSUE TITLE
Constant crashing after 1.6.0 upgrade

### ISSUE THREAD

**Issue by mattdale77** [AChep/keyguard-app#638]
I upgraded to 1.6.0 and now the app keeps crashing 

Android 14
Oppo Find X5 Pro

**Comment by AChep** [comment]
Fixed in 1.6.1

**Comment by mattdale77** [comment]
Great, when do you think this will be released?

**Comment by AChep** [comment]
This is already released everywhere except the F-Droid. I'm currently having problems with the fdroid's deployment script not working after updating to the latest Android Gradle plugin. I'll write an update here when it's fixed.

**Comment by AChep** [comment]
Managed to resolve it. @mattdale77

**Comment by mattdale77** [comment]
Can confirm that I have now been able to upgrade to 1.6.2 and I have not experienced the issue since
