### ISSUE TITLE
[bug]Unable to log-in to Bitwarden Account

### ISSUE THREAD

**Issue by Thewolf2068** [AChep/keyguard-app#643]
Tried to log-in on both Windows and Android (Play Store & Github releases, different versions) and get the following error message every time:
`Socket timeout has expired [url=https://vault.bitwarden.com/identity/connect/token, socket_timeout=unknown] ms`
![grafik](https://github.com/user-attachments/assets/a865f730-f811-4926-9f18-3eebc9632f1f)
I use vault.bitwarden.com and am able to log-in there without any issues.

**Comment by parzival-cmd** [comment]
I gave the same error, first it's the sync fail issue, but when I try to re authenticate it doesn't work.
![Screenshot_20241017-152248.png](https://github.com/user-attachments/assets/68f30b20-100a-416a-b4a7-dc72fc7707ba)

**Comment by robsonware** [comment]
Same error here:

```
Socket timeout has expired [url=https://vault.bitwarden.com/identity/connect/token, socket_timeout=unknown] ms
```
App Keyguard installed minutes ago, maybe a timezone problem, but error persist (10 hours after closed issue) :/

Device: Samsung Galaxy S23

**Comment by AChep** [comment]
This is something that requires an app update. Version 1.6.3 should have this issue fixed.
