### ISSUE TITLE
Unable to Login to Bitwarden 

### ISSUE THREAD

**Issue by markbyrn** [AChep/keyguard-app#65]
I installed the app on an S23U & Pixel 8 Pro.  Got the following error when logging into Bitwarden:

"Failed to allocate a 1040 byte allocation with 133680 free bytes and 130KB until OOM, target footprint 268435456, growth limit 26843545; giving up on allocation because <1% of heap free after GC."

Wonder if it has anything to do with my KDF settings (Memory 512 MB, Iterations 10, parallelism 8)

**Comment by AChep** [comment]
Looks like the app got assigned 256mb, which is probably not enough to handle the 512mb argon2 configuration.

**Comment by AChep** [comment]
Does it fail before asking you for a 2FA (if you have one)?

**Comment by markbyrn** [comment]
> Does it fail before asking you for a 2FA (if you have one)?

yes, it fails before 2FA.

**Comment by AChep** [comment]
Then this is definitely caused by the KDF settings. Unfortunately I have no control over how much memory system lets the Keyguard use, so there's no solution from my side.

**Comment by markbyrn** [comment]
> Looks like the app got assigned 256mb, which is probably not enough to handle the 512mb argon2 configuration.

I tried changing the KDF memory to 256 - same error.

**Comment by markbyrn** [comment]
> It should be less then 256mb, as the app also needs some memory to draw itself etc.

Okay, I changed it to 128mb and it worked - thanks.

**Comment by AChep** [comment]
App should now show a proper error message if OOM happens during KDF usage https://github.com/AChep/keyguard-app/commit/51dd09a94cef15dcb4c076769278d3e8cbc52c0a
