### ISSUE TITLE
There is a problem with the search function

### ISSUE THREAD

**Issue by pesh178** [AChep/keyguard-app#677]
I created the password in the picture. When I enter 'afd' in the filter bar, the content cannot be filtered, but when I enter 'afdi', it can be displayed normally.

![S41025-18114409](https://github.com/user-attachments/assets/84edc83a-77fe-40b1-a948-b0c791d4bd5c)
![S41025-18120502](https://github.com/user-attachments/assets/ffe56788-2341-402e-8d8c-9caee85186bc)
![S41025-18121419](https://github.com/user-attachments/assets/a008c666-fa46-4f7a-82ca-cce635b4f2fd)

**Comment by AChep** [comment]
The search only searches the title if the query is <=3 symbols long.
