### ISSUE TITLE
Cannot access Vaultwarden data

### ISSUE THREAD

**Issue by xusiai** [AChep/keyguard-app#678]
Keyguard sync from self-hosted Vaultwarden instance results in an error: 

`Illegal input: Field 'Type' is required for type with serial name 'com.artemchep.keyguard.provider.bitwarden.entity.FieldEntity', but it was missing at path: $.Cipers[7].Fields[0]`

- Bitwarden's Android client works. 
- Purged Vaultwarden sessions; wiped Keyguard app data.
- Restarted Vaultwarden host. 
- Log in seem to work but the sync fails in Keyguard. 

Using latest release (2024-10-17) on Android 15 (Graphene OS).

**Comment by AChep** [comment]
Hopefully fixed by the above commit.
