### ISSUE TITLE
Browser extension just like bitwarden?

### ISSUE THREAD

**Issue by rohitghali** [AChep/keyguard-app#69]
Autofill on windows is a pain with the native application. Possibility of making a browser extension?

**Comment by AChep** [comment]
Unfortunately I don't have any experience working with browser extensions, I also don't want to deviate much from the mobile app as I have limited resources. :disappointed:

**Comment by fahadalisarwar1** [comment]
browser extension is important for security reasons, clipboard can easily be hijacked
