### ISSUE TITLE
The application loads slowly, I'm interested in the safe

### ISSUE THREAD

**Issue by NeGroRA** [AChep/keyguard-app#695]
The application loads slowly, I'm interested in the safe

**Comment by AChep** [comment]
I'll need more details.

**Comment by NeGroRA** [comment]
What I mean is that when I turn on the application and unlock it, I have to wait a minute for everything to load,Is there a way to make it load faster?
@AChep

**Comment by NeGroRA** [comment]
Because the synchronization is always running in the background when the application is turned on and that's why it loads slowly, as it seems, and there's a way to bypass it.
