### ISSUE TITLE
Unable to login in mac app

### ISSUE THREAD

**Issue by UsamaKarim** [AChep/keyguard-app#696]
The following error appear while I try to login. I am able to login in android app but not in mac app.
App version: 1.6.4

![Screenshot 2024-11-06 at 12 39 25 PM](https://github.com/user-attachments/assets/d4a119d3-8d4c-4bcf-a21c-5be9c897965a)

**Comment by AChep** [comment]
Do you use a selfhosted Bitwarden insurance?

**Comment by UsamaKarim** [comment]
> Do you use a selfhosted Bitwarden instance?

No, I tried it now again, fortunately I am able to login. I don't know what was the issue.
