### ISSUE TITLE
[BUG] Steam TOTP uses incorrect format

### ISSUE THREAD

**Issue by RubberDuckShobe** [AChep/keyguard-app#723]
**Describe the bug**
Bitwarden supports Steam's TOTP. It's a bit special in that it contains *letters* as well as numbers. The codes are 5 characters long.

However, Keyguard shows a 6-digit code made only of numbers. This format can't be used for logging into Steam.

**To Reproduce**
1. Grab the TOTP secret from the Steam Guard Android app (or elsewhere).
2. Add it to the Bitwarden entry as a URI in the form of ``Steam://YOUR_SECRET``
3. The entry will show a 6-digit number code as the verification code instead of a code in Steam's format

**Expected behavior**
I expected the code to be 5 characters long with numbers and letters

**Screenshots**
TOTP code in Keyguard
![Screenshot_20241128-145154_Keyguard~2](https://github.com/user-attachments/assets/e167635f-e893-4ee4-b9d8-2bae4e7c156d)

Example of the correct format as shown by Vaultwarden's web interface
![Screenshot_20241128-145316_Firefox Nightly~2](https://github.com/user-attachments/assets/d8adc8a8-9611-44c5-a11c-8d8f3d66ec19)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T
 - OS: Android 14 (crDroid 10.10)
 - Browser: Firefox Nightly
 - App version: 1.6

**Additional context**
I use Vaultwarden as the server.

The official Bitwarden app gets the format wrong as well, the desktop browser extension and the Vaultwarden web interface show it correctly.

Also see Bitwarden's help page on Steam TOTP: https://bitwarden.com/help/integrated-authenticator/#steam-guard-totps

**Comment by AChep** [comment]
hmm, what if you use lowercase protocol name? `steam://`

**Comment by RubberDuckShobe** [comment]
That works, awesome!

**Comment by AChep** [comment]
Since the scheme is case-insensitive, the above commit should fix it: https://www.rfc-editor.org/rfc/rfc3986#section-3.1
