### ISSUE TITLE
"Support for Disposable Email Generation via API (DuckDuckGo, Firefox Relay)"

### ISSUE THREAD

**Issue by Debik5** [AChep/keyguard-app#724]
Is your feature request related to a problem? Please describe.
I'm frustrated that the alternative Bitwarden client does not support generating disposable email addresses through API integrations like DuckDuckGo Email Protection or Firefox Relay. This feature is available in the standard Bitwarden client and is essential for managing privacy and reducing spam when signing up for new services.

Describe the solution you'd like
I would like the alternative client to implement support for disposable email generation via API keys. This would allow users to link services like DuckDuckGo or Firefox Relay and create masked email addresses directly from the password manager interface.

Describe alternatives you've considered
The only alternative is to manually access these services outside the client, generate disposable email addresses, and then copy-paste them into Bitwarden. This process is cumbersome and disrupts workflow efficiency.

Additional context
Including this feature would bring the alternative client closer to feature parity with the official Bitwarden client. It would greatly benefit users who prioritize privacy and seek a seamless experience managing disposable email addresses.

**Comment by AChep** [comment]
Keyguard > Generator > Email forwarders > Add integration
