### ISSUE TITLE
[BUG] Passkeys broken with Kanidm

### ISSUE THREAD

**Issue by griffi-gh** [AChep/keyguard-app#739]
**Describe the bug**

**To Reproduce**
1. try to log into a Kanidm instance using Keyguard, it will fail
2. Try logging in using the official app, it will succeed 

**Expected behavior**
Authentication should succeed 

**Screenshots**

https://github.com/user-attachments/assets/53ab3cbe-5302-49ba-afef-93c7d7b9da93

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - App version [e.g. 1.6]

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: OneUI 6.1, Android 14
 - Browser Firefox
 - App version 1.6.4

**Additional context**

**Comment by AChep** [comment]
What's the signature counter of the passkey? You can check it on a dialog that shows up when you click on a passkey in Keyguard.

**Comment by griffi-gh** [comment]
> What's the signature counter of the passkey? You can check it on a dialog that shows up when you click on a passkey in Keyguard.

Its at zero

![Screenshot_20241207_150850_Keyguard](https://github.com/user-attachments/assets/d4d84c0d-3181-4cdf-9ffa-6c3fe7aacf8d)
