### ISSUE TITLE
[BUG] Failed to sync after "Equivalent Domains" feature added

### ISSUE THREAD

**Issue by Natanel-Shitrit** [AChep/keyguard-app#753]
**Describe the bug**
I'm cannot sync my vault with my server after updating keyguard app.

**To Reproduce**
1. Install Keyguard before the "Equivalent Domains" feature got introduced.
2. Connect to a server.
3. Update app to version 1.7.

**Expected behavior**
Sync should work without the `globalEquivalentDomains` / `equivalentDomains` fields

**Screenshots**
![photo_5992350831535571655_y](https://github.com/user-attachments/assets/194210e0-a923-42ec-ab1a-d2f1a87965e8)

**Smartphone (please complete the following information):**
 - App version 1.7

**Additional context**
From the error I can assume the fields was not marked as optional and when the app tries to sync over a server (that existed before this feature got introduced) it fails.

I self-host and use vaultwarden server, I haven't tested this with official bitwarden servers.

**Comment by AChep** [comment]
Oh, you are right. I'll be releasing an update with a fix tomorrow.
