### ISSUE TITLE
[BUG] "Send" Create broken link

### ISSUE THREAD

**Issue by tony8077616** [AChep/keyguard-app#762]
**Describe the bug**
When I try to use "Send" to test the link, it create a broken link
The Official Bitwarden doesn't have this problem

**To Reproduce**
1. Go to 'Send'
2. Click on 'New Item'
3. Input some text and word
4. Press 'Store' and you can see the broken link

**Expected behavior**
The link may like be
`https://domain.name/#/send/secret1/secret2`
The broken link like be
`https://domain.namesecret1/secret2`
It missing
`/#/send/`

**Screenshots**
The broken link on Android
![Screenshot_20241225-001810.png](https://github.com/user-attachments/assets/6cf5a9e7-9bfb-4405-9efe-811b0fcb4d87)

The broken link on Windows 
![image](https://github.com/user-attachments/assets/80a934e5-30ca-42b2-9ee6-f02b2816e391)

The correct link on Bitwarden Android ver.
![Screenshot_20241225-001956.png](https://github.com/user-attachments/assets/069413c7-707b-44d8-8884-709e22a1ead9)

The correct link on Bitwarden Windows ver.
![image](https://github.com/user-attachments/assets/d63b84c8-d6a4-4606-b5d7-3ea5f434ceab)

**Desktop (please complete the following information):**
- OS: Windows 11
- App Version: v1.7.2-20241223

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 2
 - OS: Android 15
 - App version v1.7.2-20241223

**Additional context**
Nothing

**Comment by AChep** [comment]
Fixed by https://github.com/AChep/keyguard-app/commit/e450fb3fec856d637b42a285c3fb43ee29e61e81
