### ISSUE TITLE
Library/Default URL Overrides

### ISSUE THREAD

**Issue by mhmatthewhugley** [AChep/keyguard-app#77]
![Screenshot_20240113-091308](https://github.com/AChep/keyguard-app/assets/73258263/5f8145b7-b935-4353-acc0-f8ae66e175bf)
The examples mentioned on GitHub would be great to have in the app, at least the HTTPS one as a default option.
This could be implemented with a toggle feature, allowing users to turn it on or off.
Alternatively, it could be added via a menu library item to avoid taking up space for users who do not intend to use it.

**Comment by AChep** [comment]
As a part of the feature, https://github.com/AChep/keyguard-app/commit/fbbe27d4bc296c0bbe94151d5c5f799a315484fa this commits adds an ability to Enable/Disable the URL override without needing to add/remove it

**Comment by AChep** [comment]
As a part of the feature, https://github.com/AChep/keyguard-app/commit/a874d88e0628b516aee8c976afa30e1dd8c0f2fc this commit adds HTTPS-ify by default

**Comment by AChep** [comment]
I think what we have now should be enough (a link to the page with examples). URL Overrides is a complex feature anyway and I don't see many universal solutions.
