### ISSUE TITLE
Fdroid release?

### ISSUE THREAD

**Issue by Nathanwoodburn** [AChep/keyguard-app#78]
G'day,
Is there any plans on releasing the android APK on an fdroid repo? That will make it easier for people to install and update the app. 

Thanks

**Comment by AChep** [comment]
Not likely to happen because of the license.

**Comment by txyyh** [comment]
make own fdroid repo? you can complete its just in a new github repo

**Comment by inson1** [comment]
change license then

**Comment by AChep** [comment]
To the brave souls who want to test it out and possibly point out that the implementation is terribly wrong: http://gh.artemchep.com/keyguard-repo-fdroid/repo/ with it being automatically built from https://github.com/AChep/keyguard-repo-fdroid
