### ISSUE TITLE
Sync with self-hosted BW never finishes

### ISSUE THREAD

**Issue by aksolera** [AChep/keyguard-app#82]
Basically subj.
Interestingly enough, when I see the content of the account I see # of folders (100+) but number of logins 0.

**Comment by AChep** [comment]
How many ciphers do you have?

**Comment by aksolera** [comment]
i'm not sure what cipher is, logins? definitely a few hundreds.
I host it in a docker container - Vaultwarden Web Version 2023.10.0

**Comment by AChep** [comment]
> i'm not sure what cipher is, logins? definitely a few hundreds.
Yeah, basically all the vault items. A few hundreds should not be too much, so that's OK.

> Interestingly enough, when I see the content of the account I see # of folders (100+) but number of logins 0.
Keyguard syncs in the order: folders -> ciphers -> collections -> organizations -> sends. If you don't see ciphers, then for some reason Keyguard gets stuck there...

I might need to build a debug build/improve an ability to collect logs to help us to resolve the issue.

**Comment by kenlasko** [comment]
New user here. Found this well-regarded app via a Reddit thread. Just to add onto this. I also have my own hosted Vaultwarden instance and I'm seeing the same behaviour.  I'm assuming you are looking for the Encryption Key settings in Vaultwarden?  I'm using Argon2id with the following settings:
KDF Iterations: 3
KDF memory: 64
KDF parallelism: 4

**Comment by AChep** [comment]
> New user here. Found this well-regarded app via a Reddit thread. Just to add onto this. I also have my own hosted Vaultwarden instance and I'm seeing the same behaviour. I'm assuming you are looking for the Encryption Key settings in Vaultwarden? I'm using Argon2id with the following settings: KDF Iterations: 3 KDF memory: 64 KDF parallelism: 4
> 
> Or if you're talking about cipher suites used by my browser. I'm proxying through Traefik on K3S. My cipher suites are set to the following:
> 
> ```
>   sniStrict: true
>   minVersion: VersionTLS12
>   cipherSuites:
>     - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
>     - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
>     - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
>     - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
>     - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
>     - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
>   curvePreferences:
>     - CurveP521
>     - CurveP384
> ```

By ciphers I meant the number or logins etc. Sorry for that, internally it's all ciphers so I often call it like that :smile: 

Any chance you could create another user on your instance and check if that user works fine?

**Comment by kenlasko** [comment]
I created a new user on my instance and was able to login successfully. Added an item in my web vault and it immediately showed up in the app.

**Comment by kenlasko** [comment]
Strange....as I was troubleshooting this, I had cleared the cache and appdata to start fresh. I did my test with a dummy account, and then re-entered my real credentials. Now, its showing all my items. Odd, but hey...its working now!

**Comment by AChep** [comment]
> ....aaaand I spoke too soon. I came back to it after a few minutes and it had locked. Once I entered my fingerprint, I was back to the same screen as posted by @aksolera. So, it seems that items are syncing and the issue lies elsewhere.
> 

Could you record an ADB log of you opening the app's vault screen? Please sanitize it and send it to my email artemchep [at] gmail.com.

**Comment by avluis** [comment]
As I'm observing the same issue, I've gone ahead and sent the requested adb log to the provided address -- do let me know whatever you need to look further into this.

**Comment by AChep** [comment]
Hola! I've added a bunch of logs to this build https://github.com/AChep/keyguard-app/actions/runs/9537486348 would be great if someone could test it again and send the results to artemchep [at] gmail.com. Feel free to sanitize the logs, as those might include the email address and web vault address.

To record a log first go to Settings / Other / Logs and click Start recording, after which go ahead and try to login to the Bitwarden. Then, wait a minute or two and go back to the Logs screen and click Export button. That will archive and save the logs to your download directory.

**Comment by AChep** [comment]
Should be fixed now since https://github.com/AChep/keyguard-app/releases/tag/r20240620
