### ISSUE TITLE
Suggestion: Change the 'Card' view UX slightly

### ISSUE THREAD

**Issue by RobertHarnett** [AChep/keyguard-app#91]
Currently the UX of the card screen is a bit inconsistent with the rest of the app. While cards perhaps merit a slight layout difference due to the nature of the information being stored being different from a password, the copy button and 'on-tap' card don't match the rest of the app.

It's broken my muscle memory a few times where I've gone to copy my card number and either copied my security code, hidden the card number, or tapped to open the menu only to not see a copy button. I've attached some images to help explain:

![Current Layout](https://github.com/AChep/keyguard-app/assets/18248672/13d1de30-3c85-40f7-95ec-8f03d6961451)

As you can see above, the card number copy icon is on the left of the screen despite it always being on the right throughout the app. 

The 'Copy card number' section also shows the full card number, which while having the main number shown means at best it's just repeating the same information a second time, and at worst - if you have the card number hidden - it just reveals the full unhidden card number.

I'm aware this is dependant on the 'Conceal fields' toggle, however the hide icon is still visible on a card number even with this turned off.

![Current on-tap Layout](https://github.com/AChep/keyguard-app/assets/18248672/dddfe4ce-c2eb-40b2-b537-b8df4608e8a2)

The other inconsistency is the pop-up menu that appears on-tap. This also differs from the rest of the app and doesn't show the usual expected options. For instance you get the option to view your three digit security code in large type, but not the card number, in reality it should probably be the other way around. 

To sum it all up and make it more digestible, it basically boils down to swapping a few buttons around, as shown in my example below.

![Proposed Layout](https://github.com/AChep/keyguard-app/assets/18248672/5fec3832-caf0-40fc-8983-33903616fdea)

Now one issue I spotted with this is that the card number itself should probably get a copy option at the top of the pop-up menu to match the rest of the app.

I know this is very long winded and perhaps very nit-picky, but I wanted an excuse to practice making some Material You phone screenshot examples. Thanks once again!

**Comment by AChep** [comment]
I actually agree with everything here :smiley:

**Comment by RobertHarnett** [comment]
Oh no... you were too quick, I was editing it my mistakes :p ... I only just noticed this can be slightly dependant on if you have the 'conceal fields' option turned on, (ie: the card number is hidden on the copy button if it's turned on) but you get the gist of what I'm saying.

**Comment by AChep** [comment]
@RobertHarnett What should the items from the second section do tho? It's either just the card number or combine all the card info to something like "Visa, 4911 **** **** ****, 12/28"

**Comment by RobertHarnett** [comment]
For the 'large type' option I feel your suggestion works fine.

While I don't use the barcode or QR code feature, I feel if you do, to make it work correctly, eg: you scan a barcode to fill in a single text field - you just want the raw number, it's more a method of input then transfer/sharing of data, so combining all the data to one could negate that use case. For that I would perhaps just generate a barcode/QR of the card number. I also find the input fields of expiration dates vary in format and input methods for it to be usable in that form.

I don't know how the app is structured but If the large type view and the barcode view are done in such a way where it's not feasible for these to differ/be too much of a overhaul for a minor change, then I would suggest you just stick to purely the card number being displayed for both large type, and the barcode view.

I'll admit, I don't actually make use of these features enough to really know what would be best for this situation.

**Comment by AChep** [comment]
@RobertHarnett I think it's best to stick to card number only for those actions. This is probably what a user wants to share the most often and we can't pollute the dropdown menu with too many options.
