### ISSUE TITLE
Feature request: Implement accessibility service for autofill

### ISSUE THREAD

**Issue by StrangePeanut** [AChep/keyguard-app#98]
Seemingly 0.1% of all apps offer native password autofill support. The other 99.9% can only be autofilled using the keyboard whose autofill option doesn't always pop up.

An accessibility service for autofill as offered by the official app is especially helpful if you have many logins for a single app or site. In this scenario you'd have to either scroll horizontally to find the login you want or scroll all the way to the right to go where an accessibility service could have taken us in the first place.

Hope this will be considered.

**Comment by AChep** [comment]
Accessibility service is not intended for Autofill and a huge pain in the ass to implement and to maintain later. :skull: While I understand that native Android Autofill sucks too, the best solution is to slowly change that by spamming Google and app developers to allocate some hours to fixing their part.
